# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from osv import fields,osv
from datetime import datetime, date, time, timedelta
from dateutil.relativedelta import *



class miembro_referencial(osv.osv):
    _name = 'miembro_referencial'
    _rec_name = 'codigo'
    def _cod_familia(self, cr, uid, ids, field_name, arg, context=None):
        res = {}
        for o in self.browse(cr, uid, ids, context=context):
		    res[o.id] = '%s-%s-%s' % (o.nombres ,o.sector,o.casa_edif)
        return res
    
    _columns = {
        'nombres': fields.char('Nombres', size=100, required=True),
        'codigo': fields.function(_cod_familia, string='Cod. Familia', type="char",size=100, store=True),
        'grupo_familiar_ids': fields.one2many('grupo_familiar', 'miembro_referencial_id', 'Persona'),
        'redi_id': fields.many2one('redi', 'REDI', required=True),
        'estado_id': fields.many2one('inces_estados', 'Estado', required=True),
        'municipio_id': fields.many2one('inces_municipios', 'Municipios', required=True),
        'parroquia_id': fields.many2one('inces_parroquias', 'Parroquias', required=True),
        'sector': fields.char('Sector', size=100, required=True),
        'av_calle': fields.char('Avenida/Calle', size=100),
        'casa_edif': fields.char('Casa/Edificio', size=100, required=True),
        'numero': fields.char('Nro Casa/Edificio', size=10),
        'fundo_id': fields.many2one('fundo', 'Fundo', required=True),
        'Lugar_residencia':fields.selection([('fundo', 'Fundo'), ('zona_periferica', 'Zona Periferica')], 'Lugar de residencia', help="Se colocara el lugar de residencia del miembro referencial (Fundo o Zonas Perifericas).", required=True, states={'fundo': [('readonly', False)]}),
        'produce':fields.selection([('productiva', 'Productiva'), ('no_productiva', 'No Productiva')], 'Produce', help="Se colocara el Estatus del Fundo Zamorano en la produccion (Productiva y No Productiva).", required=True, states={'productiva': [('readonly', False)]}),
    }
    _defaults = {
       'Lugar_residencia': 'fundo',
       'produce': 'productiva',
       
   }
       
    
miembro_referencial()

class grupo_familiar(osv.osv):
    _name = 'grupo_familiar'
    _rec_name = 'nombre'
    
    
    def edad(self, cr, uid, ids, field_name, arg, context=None):
        res={}
        now = date.today()
        if isinstance(ids,(int,long)):
            ids=[ids]
        for i in ids:
            anos="Años"
            meses="Meses"
            dias="Días"
            fecha=self.browse(cr,uid,i)
            a,m,d=fecha.fecha_nac.split('-')
            fecha_nac = date(int(a),int(m),int(d))
            edad=relativedelta(now, fecha_nac)
            if edad.years==1 or edad.years==0 :
                anos="Año"
            if edad.months==1 or edad.months==0 :
                meses="Mes"
            if edad.days==1 or edad.days==0 :
                dias="Día"
            mens=" %s %s; %s %s; %s %s  " % (edad.years,anos,edad.months,meses,edad.days,dias)
            res[i]=mens
        return res
        
        
    _columns = {
        'nombre': fields.char('Nombres', size=100, required=False),
        'miembro_referencial_id': fields.many2one('miembro_referencial', 'Familia'),
        'apellidos': fields.char('Apellidos', size=100, required=False),
        'cedula': fields.char('Cedula', size=10),
        'grupo_familiar_ids': fields.one2many('grupo_familiar', 'miembro_referencial_id', 'Persona'),
        'fecha_nac': fields.date('Fecha de Nacimiento', required=False),
        'edad': fields.function(edad ,'Edad',type='char', help=' edad'),
        'genero_id': fields.many2one('genero', 'Genero', required=False),
        'estado_civil_id': fields.many2one('estado_civil', 'Estado Civil', required=False),
        'nivel_educativo_id': fields.many2one('nivel_educativo','Nivel Educativo'),
        'partido_politico_id': fields.many2one('partido_politico', 'Partido Politico'),
        'instrumento_agrario_id': fields.many2one('intrumento_agrario', 'Instrumento Agrario'),
        'correo': fields.char('Correo', size=50),
        'pasaporte': fields.char('Nro Pasaporte', size=15),
        'fecha_vence': fields.date('Fecha Vcto Pasaporte'),
        'movimiento_ids': fields.one2many('movimiento_grupo', 'grupo_familiar_id', 'Persona', required=False),
        'misiones_ids': fields.one2many('misiones_grupo', 'grupo_familiar_id', 'Persona'),
        'enf_dis_grupo_ids': fields.one2many('enf_dis_grupo', 'grupo_familiar_id', 'Persona'),
        'fundo_organizacion_grupo_ids': fields.one2many('fundo_organizacion_grupo', 'grupo_familiar_id', 'Persona'),
        'telefono_grupo_ids': fields.one2many('telefono_grupo', 'grupo_familiar_id', 'Persona'),
    }
    
    
    def calculo_edad(self, cr, uid, ids, fecha_nac, context=None):
        res={}
        now = date.today()
        anos="Años"
        meses="Meses"
        dias="Días"
        a,m,d=fecha_nac.split('-')
        fecha_nac = date(int(a),int(m),int(d))
        edad=relativedelta(now, fecha_nac)
        if edad.years==1 or edad.years==0 :
            anos="Año"
        if edad.months==1 or edad.months==0 :
            meses="Mes"
        if edad.days==1 or edad.days==0 :
            dias="Día"
        if edad.years+edad.months+edad.days>0:
                mens=" %s %s; %s %s; %s %s  " % (edad.years,anos,edad.months,meses,edad.days,dias)
        else:
            raise osv.except_osv(('Error !'), ('Fecha de nacimiendo incorrecta: %s' % fecha_nac ))
        res['edad'] = mens
        return {'value': res}
grupo_familiar()

class fundo_organizacion_grupo(osv.osv):
    _name = 'fundo_organizacion_grupo'
    _rec_name = 'fundo_id'
    #_rec_name = 'organizacion_id'
    #_rec_name = 'grupo_familiar_id'
    
    _columns = {
        'fundo_id': fields.many2one('fundo', 'Fundo', required=False),
        'organizacion_id': fields.many2one('organizacion', 'Organizacion', required=False),
        'grupo_familiar_id': fields.many2one('grupo_familiar', 'Persona'),
    }
    
fundo_organizacion_grupo()

class genero(osv.osv):
    _name = 'genero'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Nombre del Genero', size=50, required=False),
    }
    
genero()

class estado_civil(osv.osv):
    _name = 'estado_civil'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Estado Civil', size=50, required=False),
    }
    
estado_civil()

class nivel_educativo(osv.osv):
    _name = 'nivel_educativo'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Nivel Educativo', size=50, required=False),
    }
    
nivel_educativo()

class partido_politico(osv.osv):
    _name = 'partido_politico'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Partido Politico', size=100, required=False),
    }
    
partido_politico()

class intrumento_agrario(osv.osv):
    _name = 'intrumento_agrario'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Instrumento Agrario', size=100, required=False),
    }
    
intrumento_agrario()


class tipo_telefono(osv.osv):
    _name = 'tipo_telefono'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Tipo de Telefono', size=50, required=False),
    }
    
tipo_telefono()


class movimiento_grupo(osv.osv):
    _name = 'movimiento_grupo'
    _rec_name = 'nombre'
    #_rec_name = 'grupo_familiar_id'
    
    _columns = {
        'nombre': fields.char('Movimiento', size=100, required=False),
        'grupo_familiar_id': fields.many2one('grupo_familiar', 'Persona'),
    }
    
movimiento_grupo()

class mision(osv.osv):
    _name = 'mision'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Nombre Mision', size=200, required=False),
    }
    
mision()

class misiones_grupo(osv.osv):
    _name = 'misiones_grupo'
    _rec_name = 'mision_id'
    #_rec_name = 'grupo_familiar_id'
    
    _columns = {
        'mision_id': fields.many2one('mision', 'Mision', required=False),
        'grupo_familiar_id': fields.many2one('grupo_familiar', 'Persona'),
    }
    
misiones_grupo()

class enf_dis_grupo(osv.osv):
    _name = 'enf_dis_grupo'
    _rec_name = 'nombre'
    #_rec_name = 'grupo_familiar_id'
    
    _columns = {
        'nombre': fields.char('Nombre Enfermedad', size=150, required=False),
        'grupo_familiar_id': fields.many2one('grupo_familiar', 'Persona'),
        'observacion': fields.char('Observacion', size=100),
        'enfer_disc':fields.selection([('enf', 'Enfermedad'), ('dis', 'Discapacidad')], 'Produce', help="Se colocara el Estatus del Fundo Zamorano en la produccion (Productiva y No Productiva).", required=False, states={'productiva': [('readonly', False)]}),
    }
    _defaults = {
       'enfer_disc': 'enf',
       
   }
    
enf_dis_grupo()

class telefono_grupo(osv.osv):
    _name = 'telefono_grupo'
    #_rec_name = 'grupo_familiar_id'
    _rec_name = 'numero'
    #_rec_name = 'tipo_telefono_id'
    
    _columns = {
        'grupo_familiar_id': fields.many2one('grupo_familiar', 'Persona'),
        'numero': fields.char('Numero Telefono', size=15),
        'tipo_telefono_id': fields.many2one('tipo_telefono', 'Tipo de Telefono'),
    }
    
telefono_grupo()

