# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "fundo_zamorano",
        "version" : "0.6",
        "author" : "Ahida Briceño / Victor Davila",
        "website" : "http://ciara.com.ve",
        "category" : "Unknown",
        "description": """ Versión Numero 5 del modulo de Fundos Zamoranos  """,
        "depends" : ['base'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "update_xml" : [
         'data/redi.xml', 
         'data/estados.xml',
         'data/municipios.xml',
         'data/parroquias.xml',
         'fundo_zamorano_view.xml',
         'security/ir.model.access.csv',
         'security/fundo_zamorano.xml',
         'organizacion4/organizacion4_view.xml',
         'organizacion4/security/organizacion4.xml',
         'organizacion4/security/ir.model.access.csv',
         'ejecucion_fisica1/ejecucion_fisica1_view.xml',
         'ejecucion_fisica1/security/ir.model.access.csv',
         'usuarios/usuarios_view.xml',
         'asociados2/asociados2_view.xml',
        ],
        "installable": True
}
