# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from osv import fields,osv

class usuario(osv.osv):
    """usuario"""
    _name = 'usuario'
    _rec_name = 'cedula'
    #_rec_name = 'users_id'
    #_rec_name = 'redi_id'
    #_rec_name = 'estado_id'
    #_rec_name = 'municipio_id'
    #_rec_name = 'parroquia_id'
    #_rec_name = 'fundo_id'
    
    _columns = {
        'cedula': fields.char('Cedula de Identidad', size=15,required=True, help='cedula'),
        'users_id': fields.many2one('res.users', 'Nombre del Usuario', help='Usuario'),
        'redi_id': fields.many2one('redi', 'REDI', help='REDI que  esta  asociada al Fundo'),
        'estado_id': fields.many2one('inces_estados', 'Estado', help='Estado'),
        'municipio_id': fields.many2one('inces_municipios', 'Municipio', help='Municipio'),
        'parroquia_id': fields.many2one('inces_parroquias', 'Parroquia', help='Parroquia'),
        'sector': fields.char('Sector', size=200,required=False, help='sector'),
        'calle': fields.char('Calle/Avenida', size=200,required=False, help='calle'),
        'telefono': fields.char('Número de Telefono', size=20,required=False, help='apartamento'),
        'fundo_id': fields.many2one('fundo', 'Fundo Zamorano', required=False, help='Fundo Zamorano'),
        'casa/apto': fields.char('Casa/Apto', size=200,required=False, help='casa o partamento'),
        'tipo_id': fields.many2one('tipo_usuario', 'Tipo de Usuario', required=True,help='Tipo de Usuario'),
    }
    
usuario()

class tipo_usuario(osv.osv):
    """Tipo de Usuarios"""
    _name = 'tipo_usuario'
    _rec_name = 'nombre'
    
    _columns = {
        'nombre': fields.char('Tipo de Usuario', size=50, required=True, help='Tipo de Usuario'),
    }
    
tipo_usuario()




